Feature/symfony security update
halloverden/symfony-security-bundle pull request #3
Opened 2020-08-10 12:22 UTC by tomme87

Update to reflect changes in https://github.com/halloverden/symfony-security/pull/1

Wait untill that PR is merged and fix composer.json before mergeing this.

2020-08-10 12:23 UTC, tomme87 commented on composer.json
> +        "halloverden/symfony-security": "dev-feature/access-definitions-rewrite-with-definitions-in-yaml-files-and-support-scopes",
Fix this before merge

2020-08-19 13:49 UTC, erichjsonfosse requested changes

2020-08-19 13:49 UTC, erichjsonfosse commented on README.md
> +1. Create class that implements `HalloVerden\Security\Interfaces\OauthUserProviderServiceInterface`
Typo: Should be "Create a class that implements..."

2020-08-19 13:49 UTC, erichjsonfosse commented on README.md
> +Add this path for this access definition in the config file:
Typo: Should be "Add the path for..."

2020-08-19 15:06 UTC, merged